const router=require('express').Router();const auth=require('../controllers/authController');const dash=require('../controllers/dashboardController');const emp=require('../controllers/employeeController');const task=require('../controllers/taskController');const project=require('../controllers/projectController');const profile=require('../controllers/profileController');const updates=require('../controllers/updatesController');const notesController=require('../controllers/notesController');const {requireAuth,requireAdmin,requireManager,requireOnlyManager}=require('../middleware/auth');const upload=require('../middleware/upload');const {db}=require('../database/init');
router.get('/',(req,res)=>res.redirect(req.session.user?'/dashboard':'/login'));router.get('/login',auth.loginPage);router.post('/login',auth.login);router.post('/logout',requireAuth,auth.logout);router.get('/dashboard',requireAuth,(req,res,next)=>req.session.user.role==='admin'?res.redirect('/projects'):dash.index(req,res,next));
router.get('/projects',requireAuth,(req,res,next)=>req.session.user.role==='employee'?res.status(403).render('error',{message:'Access denied'}):project.list(req,res,next));router.post('/projects',requireAuth,requireAdmin,project.save);router.post('/projects/:id/updates',requireAuth,requireOnlyManager,project.addUpdate);router.get('/projects/:id',requireAuth,project.detail);
router.get('/employees',requireAuth,requireManager,emp.list);router.post('/employees/save',requireAuth,requireManager,emp.save);router.post('/employees/:id/toggle',requireAuth,requireManager,emp.toggle);router.post('/employees/:id/delete',requireAuth,requireManager,emp.remove);
router.get('/managers',requireAuth,requireAdmin,(req,res)=>res.redirect('/employees'));router.post('/managers/save',requireAuth,requireAdmin,emp.save);router.post('/managers/:id/toggle',requireAuth,requireAdmin,emp.toggle);router.post('/managers/:id/delete',requireAuth,requireAdmin,emp.remove);
router.get('/tasks',requireAuth,task.list);router.get('/tasks/:id',requireAuth,task.detail);router.post('/tasks/save',requireAuth,task.save);router.post('/tasks/routine/save',requireAuth,requireOnlyManager,task.saveRoutine);router.post('/tasks/routine/:id/toggle',requireAuth,requireOnlyManager,task.toggleRoutine);router.post('/tasks/routine/:id/delete',requireAuth,requireOnlyManager,task.deleteRoutine);router.post('/tasks/:id/forward',requireAuth,task.forward);router.post('/tasks/:id/delete',requireAuth,requireOnlyManager,task.remove);router.post('/tasks/:id/status',requireAuth,task.status);router.post('/tasks/:id/comment',requireAuth,task.comment);router.post('/tasks/:id/upload',requireAuth,upload.single('attachment'),task.upload);router.get('/attachments/:id',requireAuth,task.download);
router.get('/notes',requireAuth,notesController.list);router.get('/notes/:id',requireAuth,notesController.detail);router.post('/notes/create',requireAuth,notesController.create);router.post('/notes/:id/auto-save',requireAuth,notesController.autoSave);router.post('/notes/:id/delete',requireAuth,notesController.deleteNote);
router.get('/profile',requireAuth,profile.page);router.post('/profile',requireAuth,profile.save);router.post('/profile/password',requireAuth,profile.password);router.get('/notifications',requireAuth,async(req,res)=>{const notes=await db.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC').all(req.session.user.id);await db.prepare('UPDATE notifications SET is_read=1 WHERE user_id=?').run(req.session.user.id);res.render('notifications',{notes});});
router.get('/updates',requireAuth,requireAdmin,updates.list);router.get('/reports',requireAuth,requireOnlyManager,async(req,res)=>{const managerId=req.session.user.id;const selectedProject=req.query.project_id?Number(req.query.project_id):null;const projects=await db.prepare('SELECT id,name FROM projects WHERE manager_id=? ORDER BY name').all(managerId);let taskWhere='WHERE created_by=?';let taskArgs=[managerId];if(selectedProject){taskWhere+=' AND project_id=?';taskArgs.push(selectedProject);}const byStatus=await db.prepare(`SELECT status label,COUNT(*) value FROM tasks ${taskWhere} GROUP BY status`).all(...taskArgs);const empSql=`SELECT u.name label,COUNT(t.id) value,SUM(CASE WHEN t.status='Completed' THEN 1 ELSE 0 END) completed FROM users u LEFT JOIN tasks t ON t.assigned_to=u.id AND t.created_by=? ${selectedProject?'AND t.project_id=?':''} WHERE u.role='employee' GROUP BY u.id,u.name ORDER BY value DESC`;const empArgs=selectedProject?[managerId,selectedProject]:[managerId];const byEmployee=await db.prepare(empSql).all(...empArgs);const projSql=`SELECT p.name label,COUNT(t.id) value,SUM(CASE WHEN t.status='Completed' THEN 1 ELSE 0 END) completed FROM projects p LEFT JOIN tasks t ON t.project_id=p.id WHERE p.manager_id=? ${selectedProject?'AND p.id=?':''} GROUP BY p.id,p.name ORDER BY value DESC`;const projArgs=selectedProject?[managerId,selectedProject]:[managerId];const byProject=await db.prepare(projSql).all(...projArgs);const overdue=await db.prepare(`SELECT COUNT(*) count FROM tasks ${taskWhere} AND due_date<CURDATE() AND status NOT IN ('Completed','Cancelled')`).get(...taskArgs);const dueSoon=await db.prepare(`SELECT COUNT(*) count FROM tasks ${taskWhere} AND due_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 3 DAY) AND status NOT IN ('Completed','Cancelled')`).get(...taskArgs);res.render('reports',{projects,selectedProject:selectedProject||'',byStatus,byEmployee,byProject,overdue:Number(overdue?.count||0),dueSoon:Number(dueSoon?.count||0)});});router.get('/activity',requireAuth,requireAdmin,async(req,res)=>{const activities=await db.prepare('SELECT a.*,u.name,u.email,u.role FROM activity_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC').all();res.render('activity',{activities});});router.get('/download/apk',(req,res)=>{const path=require('path');const apkFile=path.join(__dirname,'../public/downloads/TaskManager.apk');res.download(apkFile,'TaskManager.apk');});
const master=require('../controllers/masterController');
router.get('/api/departments',requireAuth,master.getDepartmentsAPI);
router.get('/api/designations',requireAuth,master.getDesignationsAPI);
router.post('/api/departments',requireAuth,requireManager,master.createDepartmentAPI);
router.post('/api/designations',requireAuth,requireManager,master.createDesignationAPI);
router.get('/master',requireAuth,requireManager,master.masterManagementPage);
router.post('/master/departments/save',requireAuth,requireManager,master.saveDepartment);
router.post('/master/designations/save',requireAuth,requireManager,master.saveDesignation);
router.post('/master/departments/:id/toggle',requireAuth,requireManager,master.toggleDepartment);
router.post('/master/designations/:id/toggle',requireAuth,requireManager,master.toggleDesignation);

module.exports=router;

